# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/moviesdb
spring.datasource.username=postgres
spring.datasource.password=2312

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=8080

# Redis
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

